#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d dev www cmd etc ytb soc

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Autostarts
picom --config $HOME/.config/picom/picom.conf &
sleep 0.5
$HOME/.config/polybar/launch.sh
nitrogen --restore &
wal -i $HOME/background/background2.jpg -n --backend colorz &
xss-lock --transfer-sleep-lock -- i3lock -e -B 1 -k --indicator --inside-color=137cfaff --time-color=ffffff --date-color=ffffff &
udiskie &
